name: IndefiniteObservableDart
description: An Observable for Dart that never calls complete or error
version: 0.0.1
#homepage: https://www.example.com
#author: eric <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  test: "^0.12.12"

#dev_dependencies:
#  browser: ^0.10.0
#  dart_to_js_script_rewriter: ^1.0.1

#transformers:
#- dart_to_js_script_rewriter
